src/imdb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^$', 'dashboard.views.index'),
    url(r'^admin/', admin.site.urls),
    url(r'^directors/', include("directors.urls", namespace='directors')),
    url(r'^actors/', include("actors.urls", namespace='actors')),
    url(r'^movies/', include("movies.urls", namespace='movies')),
    url(r'^accounts/', include("authentication.urls", namespace='accounts')),
    url(r'^search/', 'dashboard.views.search'),
    url(r'^api/directors/', include("directors.api.urls", namespace='api-directors')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/dashboard/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

src/movies/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User


# Create your models here.

def upload_location(instance, filename):
    return "%s/%s/%s" % (instance.__class__.__name__, instance.id, filename)


class Movie(models.Model):
    name = models.CharField(max_length=120)
    plot = models.TextField()
    release_date = models.DateTimeField()
    rating = models.FloatField(default=0.0)
    photo = models.ImageField(upload_to=upload_location, blank=True, null=True,
                              width_field="width_field",
                              height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    directors = models.ManyToManyField('directors.Director')
    actors = models.ManyToManyField('actors.Actor')
    user_rating = models.ManyToManyField(User, through='MovieRating')
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __unicode__(self):
        return unicode(self.name)

    def __str__(self):
        return unicode(self.name)

    def get_absolute_url(self):
        return reverse("movies:show", kwargs={"id": self.id})


class MovieRating(models.Model):
    user = models.ForeignKey(User)
    movie = models.ForeignKey(Movie)
    rating = models.FloatField(default=0.0)


class Review(models.Model):
    user = models.ForeignKey(User)
    movie = models.ForeignKey(Movie)
    title = models.CharField(max_length=160)
    description = models.TextField()
    has_spoiler = models.BooleanField(default=False)

src/dashboard/views.py
from django.shortcuts import render
from directors.models import Director
from actors.models import Actor
from movies.models import Movie
from django.db.models import Q

# Create your views here.
def index(request):
    directors = Director.objects.all()
    movies = Movie.objects.all().prefetch_related('directors', 'actors')
    actors = Actor.objects.all()
    total_counts = {'movies': len(movies), 'directors': len(directors), 'actors': len(actors)}
    context_data = {
        'directors': directors.order_by('-id')[:2],
        'actors': actors.order_by('-id')[:2],
        'movies': movies.order_by('-id')[:2],
        'counts': total_counts
    }
    return render(request, 'dashboard/index.html', context_data)

def search(request):
    param = request.GET.get('q')
    query_movies = Q(name__icontains = param) | Q(plot__icontains = param)
    query_others = Q(name__icontains = param) | Q(bio__icontains = param)
    movies = Movie.objects.filter(query_movies)
    directors = Director.objects.filter(query_others)
    actors = Actor.objects.filter(query_others)
    total_counts = {'movies': len(movies), 'directors': len(directors), 'actors': len(actors)}
    # print total_counts
    context_data = {
        'directors': directors.order_by('-id'),
        'actors': actors.order_by('-id'),
        'movies': movies.order_by('-id'),
        'counts': total_counts
    }
    return render(request, 'dashboard/search_results.html', context_data)

src/templates/dashboard/index.html
{% extends 'layouts/base.html' %}

{% block content %}

    <div class="row all-movies">
        {% for movie in movies %}
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <div class="info-box brown-bg">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            {% if movie.photo %}
                                <img src="{{ movie.photo.url }}" class="img-responsive">
                            {% endif %}
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="count">
                                <a href="{{ movie.get_absolute_url }}">{{ movie.name }}</a>
                            </div>
                            <div>{{ movie.plot | truncatechars:100 }}</div>
                            <br>
                            <div class="title">
                                <strong>Director: </strong>
                                {% for director in movie.directors.all %}
                                    <a href="{{ director.get_absolute_url }}">{{ director.name }}</a><br>
                                {% endfor %}
                            </div>
                            <div class="title">
                                <strong>Cast: </strong>
                                {% for actor in movie.actors.all %}
                                    <a href="{{ actor.get_absolute_url }}">{{ actor.name }}</a><br>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <div class="info-box-custom green-bg">
                <i class="fa fa-cubes"></i>
                <div class="count">{{ counts.movies }}</div>
                <div class="title">Movies</div>
            </div>
        </div>
    </div>

    <div class="row all-directors">
        {% for director in directors %}
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <div class="info-box brown-bg">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            {% if director.photo %}
                                <img src="{{ director.photo.url }}" class="img-responsive">
                            {% endif %}
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="count">
                                <a href="{{ director.get_absolute_url }}">{{ director.name }}</a>
                            </div>
                            <div>{{ director.bio | truncatechars:100 }}</div>
                            <br>
                            <div class="title">
                                <strong>Movies: </strong>
                                {% for movie in director.movie_set.all %}
                                    <a href="{{ movie.get_absolute_url }}">{{ movie.name }}</a><br>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <div class="info-box-custom green-bg">
                <i class="fa fa-cubes"></i>
                <div class="count">{{ counts.directors }}</div>
                <div class="title">Directors</div>
            </div>
        </div>
    </div>

    <div class="row all-actors">
        {% for actor in actors %}
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <div class="info-box brown-bg">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            {% if actor.photo %}
                                <img src="{{ actor.photo.url }}" class="img-responsive">
                            {% endif %}
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="count">
                                <a href="{{ actor.get_absolute_url }}">{{ actor.name }}</a>
                            </div>
                            <div>{{ actor.bio | truncatechars:100 }}</div>
                            <br>
                            <div class="title">
                                <strong>Movies: </strong>
                                {% for movie in actor.movie_set.all %}
                                    <a href="{{ movie.get_absolute_url }}">{{ movie.name }}</a><br>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <div class="info-box-custom green-bg">
                <i class="fa fa-cubes"></i>
                <div class="count">{{ counts.actors }}</div>
                <div class="title">Actors</div>
            </div>
        </div>
    </div>

{% endblock content %}

src/templates/dashboard/search_results.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading tab-bg-info">
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a data-toggle="tab" href="#recent-activity">
                                <i class="fa fa-video-camera"></i>
                                Movies
                            </a>
                        </li>
                        <li>
                            <a data-toggle="tab" href="#profile">
                                <i class="fa fa-users"></i>
                                Directors
                            </a>
                        </li>
                        <li class="">
                            <a data-toggle="tab" href="#edit-profile">
                                <i class="fa fa-star"></i>
                                Actors
                            </a>
                        </li>
                    </ul>
                </header>
                <div class="panel-body">
                    <div class="tab-content">
                        <div id="recent-activity" class="tab-pane active">
                            <div class="profile-activity">
                                {% for movie in movies %}
                                    <div class="act-time">
                                        <div class="activity-body act-in">
                                            <span class="arrow"></span>
                                            <div class="text">
                                                <a href="{{ movie.get_absolute_url }}" class="activity-img"><img class="avatar"
                                                                                      src="{{ movie.photo.url }}" alt=""></a>
                                                <p class="attribution"><a
                                                        href="{{ movie.get_absolute_url }}">{{ movie.name }}</a>
                                                    released {{ movie.release_date }}</p>
                                                <p>{{ movie.plot }}</p>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>

                        </div>

                        <!-- directors -->
                        <div id="profile" class="tab-pane">
                            {% for director in directors %}
                                <div class="act-time">
                                    <div class="activity-body act-in">
                                        <span class="arrow"></span>
                                        <div class="text">
                                            <a href="{{ director.get_absolute_url }}" class="activity-img"><img class="avatar"
                                                                                  src="{{ director.photo.url }}" alt=""></a>
                                            <p class="attribution"><a
                                                    href="{{ director.get_absolute_url }}">{{ director.name }}</a></p>
                                            <p>{{ director.bio }}</p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>

                        <!-- Actors -->
                        <div id="edit-profile" class="tab-pane">
                            {% for actor in actors %}
                                <div class="act-time">
                                    <div class="activity-body act-in">
                                        <span class="arrow"></span>
                                        <div class="text">
                                            <a href="{{ actor.get_absolute_url }}" class="activity-img"><img class="avatar"
                                                                                  src="{{ actor.photo.url }}" alt=""></a>
                                            <p class="attribution"><a
                                                    href="{{ actor.get_absolute_url }}">{{ actor.name }}</a></p>
                                            <p>{{ actor.bio }}</p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
{% endblock content %}