src/imdb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^$', 'dashboard.views.index'),
    url(r'^admin/', admin.site.urls),
    url(r'^directors/', include("directors.urls", namespace='directors')),
    url(r'^actors/', include("actors.urls", namespace='actors')),
    url(r'^movies/', include("movies.urls", namespace='movies')),
    url(r'^accounts/', include("authentication.urls", namespace='accounts')),
    url(r'^search/', 'dashboard.views.search'),
    url(r'^api/directors/', include("directors.api.urls", namespace='api-directors')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/movies/urls.py
from django.conf.urls import url

from .views import (
    movies_index,
    movie_show,
    movie_rating,
    create_movie_review,
    edit_movie_review,
    delete_movie_review
)

urlpatterns = [
    url(r'^$', movies_index),
    url(r'^(?P<id>\d+)/$', movie_show, name='show'),
    url(r'^(?P<id>\d+)/rating/$', movie_rating, name='rating'),
    url(r'^(?P<id>\d+)/review/$', create_movie_review, name='new_review'),
    url(r'^(?P<movie_id>\d+)/reviews/(?P<id>\d+)$', edit_movie_review, name='edit_review'),
    url(r'^(?P<movie_id>\d+)/reviews/(?P<id>\d+)/delete$', delete_movie_review, name='delete_review'),
]

src/movies/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User


# Create your models here.

def upload_location(instance, filename):
    return "%s/%s/%s" % (instance.__class__.__name__, instance.id, filename)


class Movie(models.Model):
    name = models.CharField(max_length=120)
    plot = models.TextField()
    release_date = models.DateTimeField()
    rating = models.FloatField(default=0.0)
    photo = models.ImageField(upload_to=upload_location, blank=True, null=True,
                              width_field="width_field",
                              height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    directors = models.ManyToManyField('directors.Director')
    actors = models.ManyToManyField('actors.Actor')
    user_rating = models.ManyToManyField(User, through='MovieRating')
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __unicode__(self):
        return unicode(self.name)

    def __str__(self):
        return unicode(self.name)

    def get_absolute_url(self):
        return reverse("movies:show", kwargs={"id": self.id})


class MovieRating(models.Model):
    user = models.ForeignKey(User)
    movie = models.ForeignKey(Movie)
    rating = models.FloatField(default=0.0)


class Review(models.Model):
    user = models.ForeignKey(User)
    movie = models.ForeignKey(Movie)
    title = models.CharField(max_length=160)
    description = models.TextField()
    has_spoiler = models.BooleanField(default=False)

src/movies/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse
from .models import Movie, MovieRating, Review
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Avg
from django.http import HttpResponseRedirect

# Create your views here.

def movies_index(request):
    movies = Movie.objects.all().prefetch_related('directors', 'actors')

    context_data = {
        'movies': movies
    }

    return render(request, 'movies/index.html', context_data)


def movie_show(request, id=None):
    movie = get_object_or_404(Movie.objects.prefetch_related('directors', 'actors', 'review_set'), id=id)
    context_data = {
        'movie': movie,
        'title': movie.name,
        'rating': get_movie_rating(request, movie)
    }
    return render(request, 'movies/show.html', context_data)


def movie_rating(request, id=None):
    movie = get_object_or_404(Movie.objects, id=id)
    if request.is_ajax():
        ratings_given = float(request.GET['rating'])
        try:
            movie_rating = MovieRating.objects.get(user=request.user, movie=movie)
            movie_rating.rating = ratings_given
            movie_rating.save()
            update_movie_rating(movie)
        except ObjectDoesNotExist:
            MovieRating.objects.create(user_id=request.user.id, movie_id=movie.id, rating=ratings_given)
            update_movie_rating(movie)

        return JsonResponse({'rating': ratings_given})
    return JsonResponse({'rating': movie.rating})


def create_movie_review(request, id=None):
    movie = get_object_or_404(Movie.objects, id=id)
    has_spoiler = 0 if 'has_spoiler' not in request.POST else request.POST['has_spoiler']
    Review.objects.create(user_id=request.user.id, movie_id=movie.id,
                          title=request.POST['title'], description=request.POST['description'],
                          has_spoiler=has_spoiler)
    return HttpResponseRedirect(movie.get_absolute_url())


def edit_movie_review(request, movie_id=None, id=None):
    movie = get_object_or_404(Movie.objects, id=movie_id)
    review = get_object_or_404(Review.objects, id=id)
    review.title = request.POST['title']
    review.description = request.POST['description']
    review.has_spoiler = 0 if 'has_spoiler' not in request.POST else request.POST['has_spoiler']
    review.save(update_fields=['title', 'description', 'has_spoiler'])

    return HttpResponseRedirect(movie.get_absolute_url())

def delete_movie_review(request, movie_id=None, id=None):
    movie = get_object_or_404(Movie.objects, id=movie_id)
    review = get_object_or_404(Review.objects, id=id)
    review.delete()
    return HttpResponseRedirect(movie.get_absolute_url())

def update_movie_rating(movie):
    result = MovieRating.objects.filter(movie_id=movie.id).aggregate(Avg('rating'))
    movie.rating = result['rating__avg']
    movie.save(update_fields=['rating'])

def get_movie_rating(request, movie):
    if request.user.is_authenticated():
        rating = MovieRating.objects.filter(user=request.user, movie=movie)
        if len(rating) > 0:
            return rating[0].rating

    return movie.rating

src/templates/movies/index.html
{% extends 'layouts/base.html' %}

{% block content %}

    <div class="row all-movies">
        {% for movie in movies %}
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <div class="info-box brown-bg">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            {% if movie.photo %}
                                <img src="{{ movie.photo.url }}" class="img-responsive">
                            {% endif %}
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="count">
                                <a href="{{ movie.get_absolute_url }}">{{ movie.name }}</a>
                            </div>
                            <div>{{ movie.plot | truncatechars:100 }}</div>
                            <div class="title">
                                <strong>Director: </strong>
                                {% for director in movie.directors.all %}
                                    <a href="{{ director.get_absolute_url }}">{{ director.name }}</a><br>
                                {% endfor %}
                            </div>
                            <div class="title">
                                <strong>Cast: </strong>
                                {% for actor in movie.actors.all %}
                                    <a href="{{ actor.get_absolute_url }}">{{ actor.name }}</a><br>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock content %}

src/templates/movies/reviews.html
{% load staticfiles %}
<div class="col-md-12 portlets">
    <!-- Widget -->
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="pull-left">Reviews</div>
            <div class="clearfix"></div>
        </div>

        <div class="panel-body">
            <!-- Widget content -->
            <div class="padd sscroll">

                <ul class="chats">

                    {% for review in movie.review_set.all %}

                        <!-- Chat by us. Use the class "by-me". -->
                        <li class="by-me" id="review_{{ review.id }}">
                            <!-- Use the class "pull-left" in avatar -->
                            <div class="avatar pull-left">
                                <img src="{% static "img/avatar1_small.jpg" %}" alt=""/>
                            </div>

                            <div class="chat-content">
                                <!-- In meta area, first include "name" and then "time" -->
                                <div class="chat-meta">
                                    <span class="title">{{ review.title }}</span>
                                    {% if review.has_spoiler %} <span><b>Review contains spoiler</b></span>{% endif %}
                                    {% if review.user == user %}
                                        <span class="pull-right">
                                        <a href="{% url 'movies:delete_review' movie_id=movie.id id=review.id %}">
                                            <i class="fa fa-trash-o"></i> Delete
                                        </a>
                                        <a onclick="openEditForm({{ review.id }})">
                                            <i class="fa fa-pencil-square"></i> Edit
                                        </a>
                                        </span>
                                    {% endif %}
                                </div>
                                <span class="descrip">{{ review.description }}</span>
                                <div class="clearfix"></div>
                            </div>
                        </li>

                    {% endfor %}

                </ul>

            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="review_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="form quick-post">
            <!-- Edit profile form (not working)-->
            <form class="form-horizontal review-form">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"
                                aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Your Review</h4>
                    </div>
                    <div class="modal-body">
                        {% csrf_token %}
                        <!-- Title -->
                        <div class="form-group">
                            <label class="control-label col-lg-2" for="title">Title</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" id="title" name="title" required>
                            </div>
                        </div>
                        <!-- Content -->
                        <div class="form-group">
                            <label class="control-label col-lg-2" for="content">Content</label>
                            <div class="col-lg-10">
                                <textarea class="form-control" id="content"
                                          rows="6" name="description" required></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-lg-2" for="tags">Has Spoiler?</label>
                            <div class="col-lg-10">
                                <input type="checkbox" name="has_spoiler" />
                            </div>
                        </div>

                    </div>

                    <div class="modal-footer">
                        <button data-dismiss="modal" class="btn btn-default" type="button">Close
                        </button>
                        <button class="btn btn-warning" type="submit"> Save</button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

src/templates/movies/show.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="row single-movie">

        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="count">
                {{ movie.name }}
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div id="movie-rating"></div>
                </div>
                <div class="col-md-2">
                    <h3 id="movie-rating-number">{{ rating }}</h3>
                </div>
            </div>
            <div>{{ movie.plot }}</div>
            <div class="title">
                <strong>Director: </strong>
                {% for director in movie.directors.all %}
                    <a href="{{ director.get_absolute_url }}">{{ director.name }}</a><br>
                {% endfor %}
            </div>
            <div class="title">
                <strong>Cast: </strong>
                {% for actor in movie.actors.all %}
                    <a href="{{ actor.get_absolute_url }}">{{ actor.name }}</a><br>
                {% endfor %}
            </div>

            {% if user.is_authenticated %}
                <div class="review-add-btn">
                    <a class="btn btn-success" onclick="openReviewModal()">
                        <i class="fa fa-plus"></i> Add Review
                    </a>
                </div>
            {% endif %}

        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
            {% if movie.photo %}
                <img src="{{ movie.photo.url }}" class="img-responsive movie-poster">
            {% endif %}
        </div>

    </div>
    <div class="row reviews">
        {% include 'movies/reviews.html' %}
    </div>
{% endblock content %}

{% block javascript %}
    <script>
        $("#movie-rating").rateYo({
            rating: {{ rating }},
            numStars: 10,
            halfStar: true,
            precision: 1,
            maxValue: 10,
            {% if user.is_authenticated %}
                onSet: function (rating, rateYoInstance) {
                    $.ajax({
                        url: "/movies/{{ movie.id }}/rating",
                        type: "GET",
                        data: {rating: rating},
                        success: function (response) {
                            document.getElementById('movie-rating-number').innerHTML = response['rating'];
                        }
                    });
                }
            {% endif %}
        });
    
    function openEditForm(review_id) {
        $('#review_modal').modal('show');
        $('.review-form').attr('action', '/movies/{{ movie.id }}/reviews/' + review_id);
        $(".review-form").attr("method", "post");
        review_id = "#review_" + review_id;
        var title = $(review_id + ' .title').html();
        var des = $(review_id + ' .descrip').html();
        var spoiler = $(review_id).find('b')[0] == null ? false : true;
        $('#review_modal #title').val(title);
        $('#review_modal #content').val(des);
        if(spoiler)
            $("#review_modal input[type='checkbox']").prop("checked", true);
        else
           $("#review_modal input[type='checkbox']").prop("checked", false);
    }

    function openReviewModal() {
        $('#review_modal').modal('show');
        $('.review-form').attr('action', '/movies/{{ movie.id }}/review/');
        $(".review-form").attr("method", "post");
        $('#review_modal #title').val('');
        $('#review_modal #content').val('');
        $("#review_modal input[type='checkbox']").prop("checked", false);
    }

    </script>
{% endblock %}