src/authentication/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^register/$', 'authentication.views.register', name='register'),
    url(r'^register/complete/$', 'authentication.views.registration_complete',
        name='registration_complete'),
    url(r'^login/$', 'authentication.views.login_user', name='login'),
    url(
        r'^logout/$',
        'django.contrib.auth.views.logout',
        name='logout',
        kwargs={'next_page': '/movies'}
    ),
]

src/imdb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^$', 'dashboard.views.index'),
    url(r'^admin/', admin.site.urls),
    url(r'^directors/', include("directors.urls", namespace='directors')),
    url(r'^actors/', include("actors.urls", namespace='actors')),
    url(r'^movies/', include("movies.urls", namespace='movies')),
    url(r'^accounts/', include("authentication.urls", namespace='accounts')),
    url(r'^search/', 'dashboard.views.search'),
    url(r'^api/directors/', include("directors.api.urls", namespace='api-directors')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/layouts/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="author" content="GeeksLabs">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <link rel="shortcut icon" href="{% static "img/favicon.ico" %}">

    <title>IMDb | Movie Database</title>

    <!-- Bootstrap CSS -->
    <link rel='stylesheet' href='{% static "css/bootstrap.min.css" %}'/>
    <!-- bootstrap theme -->
    <link rel='stylesheet' href='{% static "css/bootstrap-theme.css" %}'/>
    <!--external css-->
    <link rel='stylesheet' href='{% static "css/rating.css" %}'/>
    <!-- font icon -->
    <link rel='stylesheet' href='{% static "css/elegant-icons-style.css" %}'/>
    <link rel='stylesheet' href='{% static "css/font-awesome.min.css" %}'/>
    <!-- Custom styles -->
    <link rel='stylesheet' href='{% static "css/style.css" %}'/>
    <link rel='stylesheet' href='{% static "css/style-responsive.css" %}'/>
    <link rel='stylesheet' href='{% static "css/custom.css" %}'/>

    <!-- javascripts -->
    <script src="{% static "js/jquery.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/rating.js" %}"></script>
    <!-- nicescroll -->
    <script src="{% static "js/jquery.scrollTo.min.js" %}"></script>
    <script src="{% static "js/jquery.nicescroll.js" %}" type="text/javascript"></script>
    <!--custome script for all page-->
    <script src="{% static "js/scripts.js" %}"></script>


</head>

<body>
<!-- container section start -->
<section id="container" class="">

    <!--header start-->
    {% include "layouts/topbar.html" %}
    <!--header end-->

    <!--sidebar start-->
    {% include "layouts/sidebar.html" %}
    <!--sidebar end-->

    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
            {% block content %}{% endblock content %}
        </section>
    </section>
    <!--main content end-->

</section>
{% block javascript %}{% endblock %}
</body>
</html>

src/templates/layouts/base_authentication.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="author" content="GeeksLabs">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <link rel="shortcut icon" href="{% static "img/favicon.ico" %}">

    <title>IMDb | Authorization</title>

    <!-- Bootstrap CSS -->
    <link rel='stylesheet' href='{% static "css/bootstrap.min.css" %}'/>
    <!-- bootstrap theme -->
    <link rel='stylesheet' href='{% static "css/bootstrap-theme.css" %}'/>
    <!--external css-->
    <!-- font icon -->
    <link rel='stylesheet' href='{% static "css/elegant-icons-style.css" %}'/>
    <link rel='stylesheet' href='{% static "css/font-awesome.min.css" %}'/>
    <!-- Custom styles -->
    <link rel='stylesheet' href='{% static "css/style.css" %}'/>
    <link rel='stylesheet' href='{% static "css/style-responsive.css" %}'/>
    <link rel='stylesheet' href='{% static "css/custom.css" %}'/>


</head>

<body class="login-img3-body">

<div class="container">
    {% block content %}{% endblock content %}
</div>
</div>

</body>
</html>

src/templates/layouts/sidebar.html
<aside>
    <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu">
            <li class="">
                <a class="" href="/">
                    <i class="fa fa-dashboard"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li>
                <a class="" href="/movies">
                    <i class="fa fa-video-camera"></i>
                    <span>Movies</span>
                </a>
            </li>
            <li>
                <a class="" href="/directors">
                    <i class="fa fa-users"></i>
                    <span>Directors</span>
                </a>
            </li>
            <li>
                <a class="" href="/actors">
                    <i class="fa fa-star"></i>
                    <span>Actors</span>
                </a>
            </li>

{#            <li class="sub-menu">#}
{#                <a href="javascript:;" class="">#}
{#                    <i class="icon_table"></i>#}
{#                    <span>Tables</span>#}
{#                    <span class="menu-arrow arrow_carrot-right"></span>#}
{#                </a>#}
{#                <ul class="sub">#}
{#                    <li><a class="active" href="basic_table.html">Basic Table</a></li>#}
{#                </ul>#}
{#            </li>#}

        </ul>
        <!-- sidebar menu end-->
    </div>
</aside>

src/templates/layouts/topbar.html
{% load staticfiles %}
<header class="header dark-bg">
    <div class="toggle-nav">
        <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i
                class="icon_menu"></i></div>
    </div>

    <!--logo start-->
    <a href="/" class="logo">Django <span class="lite">IMDb</span></a>
    <!--logo end-->

    <div class="nav search-row" id="top_menu">
        <!--  search form start -->
        <ul class="nav top-menu">
            <li>
                <form class="navbar-form" action="/search" method="get">
                    <input id="search-type" class="form-control" placeholder="Search" type="text" name="q">
                </form>
            </li>
        </ul>
        <!--  search form end -->
    </div>

    <div class="top-nav notification-row">
        <!-- notificatoin dropdown start-->
        <ul class="nav pull-right top-menu">

            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="profile-ava">
                                <img alt="" src="{% static "img/avatar1_small.jpg" %}">
                            </span>
                    <span class="username">
                        {% if user.is_authenticated %}
                            {{ user.username }}
                        {% else %}
                            Guest
                        {% endif %}
                    </span>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu extended logout">
                    <div class="log-arrow-up"></div>
                    <li class="eborder-top">
                        <a href="#"><i class="icon_profile"></i> My Profile</a>
                    </li>
                    <li>
                        <a href="#"><i class="icon_mail_alt"></i> My Inbox</a>
                    </li>
                    <li>
                        <a href="#"><i class="icon_clock_alt"></i> Timeline</a>
                    </li>
                    <li>
                        <a href="#"><i class="icon_chat_alt"></i> Chats</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'accounts:logout' %}"><i class="icon_key_alt"></i>
                                Log Out</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'accounts:login' %}"><i class="icon_key_alt"></i>
                                Login</a>
                        </li>
                    {% endif %}
                    <li>
                        <a href="documentation.html"><i class="icon_key_alt"></i> Documentation</a>
                    </li>
                    <li>
                        <a href="documentation.html"><i class="icon_key_alt"></i> Documentation</a>
                    </li>
                </ul>
            </li>
            <!-- user login dropdown end -->
        </ul>
        <!-- notificatoin dropdown end-->
    </div>
</header>